#!/bin/bash

CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}#### BUILD ####${NC}"

swift build

echo -e "\n"

echo -e "${CYAN}#### RUN ####${NC}"

.build/debug/swift-syntax-check Tests/Sample.swift

echo -e "\n"
