#!/bin/bash

CYAN='\033[0;36m'
NC='\033[0m'

TARGET_DIR='Sources'

echo -e "${CYAN}START${NC}: fswatch ${TARGET}"

fswatch -e '.*' -i '\.swift$' ${TARGET_DIR} | xargs -I{} ./build_and_run

echo -e "\n"
